### ISSUE TITLE
wrong order of rows and cols size for width anf hight of the board

### ISSUE THREAD

**Issue by Drachenbauer** [janbodnar/Java-Minesweeper-Game#2]
private final int BOARD_WIDTH = N_ROWS * CELL_SIZE + 1;
private final int BOARD_HEIGHT = N_COLS * CELL_SIZE + 1;

You must switch N_COLS and N_ROWS in this two lines.

otherwhise, it will not work with a rectangular game-setup (for sample 12 * 20 cells)

**Comment by janbodnar** [comment]
I have corrected it. Thanks.
